version: '3.9'

services:
  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8086:8080"
    volumes:
      - ./etc:/usr/lib/trino/etc:ro
      - ./catalog:/etc/trino/catalog
      - ./config:/etc/trino/config
    depends_on:
      - clickhouse
      - postgres
    networks:
      - trino_network
  

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      # - "9000:9000"
      - "9009:9009"
    environment:
      CLICKHOUSE_DB: default_db
      CLICKHOUSE_USER: default_user
      CLICKHOUSE_PASSWORD: default_password
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8123/ping | grep -q Ok"]
      interval: 10s
      retries: 5
    restart: always
    networks:
      - trino_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: trino_user
      POSTGRES_PASSWORD: trino_password
      POSTGRES_DB: trino_db
    ports:
      - "5432:5432"
    networks:
      - trino_network

  # mariadb:
  #   hostname: mariadb
  #   image: mariadb:10.5.8
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #     MYSQL_DATABASE: metastore_db
  #   networks:
  #     - trino_network

  metastore_db:
    image: postgres:latest
    hostname: metastore_db
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5433:5432"
    networks:
      - trino_network

  hive-metastore:
    hostname: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: metastore_db
    depends_on:
      - metastore_db
    networks:
      - trino_network

  minio:
    hostname: minio
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":9001"
    networks:
      - trino_network


volumes:
  minio-data:
    driver: local

networks:
  trino_network:
    driver: bridge
